version: '3'
networks:
    cluster:
        external:
            name: cluster
services:
    mongo:
        container_name: "mongo"
        networks:
          cluster:
            ipv4_address: 10.100.100.2
            aliases:
              - mongo
        image: mongo
    mariadb:
        container_name: "mariadb"
        networks:
          cluster:
            ipv4_address: 10.100.100.3
            aliases:
              - mariadb
        image: mariadb
        ports:
          - "3306:3306"
        volumes:
            - /root/ZADANIE:/DATA
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: LAB_KAMIL
        healthcheck:
          test: ["CMD", "mysql", "--user=root", "-proot", "-e show databases"]
          interval: 2s
          timeout: 1s
          retries: 20
    python:
        container_name: "python"
        networks:
          cluster:
            ipv4_address: 10.100.100.4
            aliases:
              - python
        image: deb_py
        volumes:
            - /root/ZADANIE:/PY3
        command: tail -f /etc/passwd > /dev/null